# Generated by Django 2.2.16 on 2022-05-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220525_0103'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_name_unique',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='%(app_label)s_%(class)s_name_unique'),
        ),
    ]
