# Generated by Django 2.2.16 on 2022-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220525_1706'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_name_unique',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_name_following'),
        ),
    ]
